### ISSUE TITLE
improve default behavior if user forgets `--point_arrays` in teca_temporal_reduce

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#753] opened 2023-05-30 19:54 UTC
If a user forgets to add the `--point_arrays` argument to `teca_temporal_reduce` or `teca_cpp_temporal_reduce`, the pipeline runs an immediately hits the error message `ERROR: Failed to locate index_initializer_key`.  This would be confusing to most novice users.

I recommend one of two default behaviors:

1. (simplest) check the number of arguments to `--point_arrays` to make sure at least one variable is present
2. (most intuitive - to me at least) -- default to reducing all available point arrays

**Comment by burlen** [comment] 2023-05-30 22:01
good point, this could and should be handled in the application code that deals command line argument parsing. both of your suggestions are doable.

**Comment by taobrienlbl** [comment] 2023-06-01 16:19
this was `teca_cpp_temporal_reduction` specifically--though I thought I had run into this with the python version, but perhaps I was mistaken there.

**Comment by taobrienlbl** [comment] 2023-06-01 16:23
and to clarify, this was built against commit f2ef981

**Comment by burlen** [comment] 2023-06-01 16:29
OK, so it sounds like your problem was with the command line application then.

 There are some missing checks in both the C++ version of the algorithm and the C++ version of the applicaiton. I'm adding them now. 

I also see that some of the sanity checks in the Python implementation, test for None (what occurs if nothing is set) and  don't catch when an empty list is passed. I'll update that as well.

**Comment by burlen** [comment] 2023-06-01 16:29
I'm testing on the same commit

**Comment by taobrienlbl** [comment] 2023-06-01 16:34
cool, thanks!

**Comment by burlen** [comment] 2023-06-01 16:39
Ah, I was able to reproduce this with the `teca_cpp_temporal_reduction`.  What you're describing happens when both `--point_arrays` and `--verbose` flags are missing (it's an unlucky coincidence that I tested with `--verbose`). Here is the full error message (always useful to see all the info since class name and line number are included):
```
ERROR: [0:140616631919360] [/home/bloring/work/teca/TECA_abdel/alg/teca_temporal_reduction.cxx:1786 4.0.0-583-gbd4eaa8]
ERROR: No point arrays were specified

ERROR: [0:140616631919360] [/home/bloring/work/teca/TECA_abdel/io/teca_cf_writer.cxx:328 4.0.0-583-gbd4eaa8]
ERROR: Failed to locate index_initializer_key
```

**Comment by taobrienlbl** [comment] 2023-06-01 16:39
Also, in case it is useful, here's the specific command & output I was testing on that generated this.  I'll note though that I apparently missed in my original report that the error message does indeed report 'ERROR: no arrays specified'; apologies for overlooking that.  FWIW, this is being run on IU's [Big Red 200](https://kb.iu.edu/d/brcc) on 4 GPU nodes

```bash
srun -n 16 teca_cpp_temporal_reduction --input_regex '/N/project/obrienta_startup/datasets/ERA5/ds633.0/e5.oper.an.pl/202011/e5.oper.an.pl.128_060_pv.ll025sc.*\.nc' --output_file "e5.oper.an.pl.128_060_pv.ll025sc.%t%.nc" --steps_per_file 1000000 --interval monthly --operator average --x_axis_variable longitude --y_axis_variable latitude --z_axis_variable level
ERROR: [10:140707138813952] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [6:140691715923968] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: [0:140023864930304] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [12:140707480530944] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [11:140123037777920] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [7:140113250168832] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [2:140228451520512] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [13:140488291573760] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [8:140296531849216] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [4:139706819686400] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [3:139763822927872] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [15:139962210230272] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [9:139702336708608] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: [5:139651045179392] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [1:140502467342336] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: [14:140706387992576] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/alg/teca_temporal_reduction.cxx:1786 4.0.0-572-gf2ef981]
ERROR: No arrays specified
ERROR: No arrays specified
ERROR: No arrays specified

ERROR: [6:140691715923968] [/N/u/obrienta/BigRed200/slate_obrienta/teca_development/bigred200/TECA_src/io/teca_cf_writer.cxx:328 4.0.0-572-gf2ef981]
ERROR: Failed to locate index_initializer_key

aborting ...
```

(and then there's much more output, mostly repeating error messages across ranks)

The same command works if I add `--point_arrays PV` to the command line.

**Comment by burlen** [comment] 2023-06-01 16:41
Yes, this is the same. the first error should terminate the program. Also, we should look at the CF writer since this is indeed a confusing error message, and the CF writer also depends on having the point arrays explicitly set.

**Comment by taobrienlbl** [comment] 2023-06-01 16:47
cool, glad we are on the same page wrt the error message (I missed your earlier one indicating you had reproduced it).
Also good to know that `--verbose` might change the error message behavior.  That hadn't occurred to me

**Comment by burlen** [comment] 2023-06-01 16:47
Looking at the cf_writer, the error there is due to empty metadata, which is a result of the cpp temporal_reduction not handling the error correctly. Fixing that will also prevent the confusing cf_writer issue. However, I'll add some detail to the cf_writer error message to guide the user to the source.

**Comment by taobrienlbl** [comment] 2023-06-01 16:49
ah, I see!

**Comment by burlen** [comment] 2023-06-01 16:52
The OOM must have been frustrating. I'm glad the spatial partitioning worked, this is why we developed it! I'm not sure what we can do to prevent the OOM since it depends on many factors including the amount of on node ram, how the MPI processes are assigned to nodes, the time range of the reduction (longer is more likely to OOM), and the size of the input data. It may be worth adding a note in the user guide to the affect that when OOM is encountered, the spatial partitioning may help (with some details).

**Closed** 2023-06-01 23:15 UTC
Labels: bug, feature, 2_medium_priority, temporal reductions, good first issue
