### ISSUE TITLE
Python 3 not found on Mac OS Travis CI

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#321] opened 2020-01-24 17:35 UTC
```
-- Could NOT find PythonInterp: Found unsuitable version "2.7.17", but required is at least "3" (found /usr/local/bin/python)
-- Could NOT find PythonLibs: Found unsuitable version "2.7.10", but required is at least "3" (found /usr/lib/libpython2.7.dylib)
-- Could NOT find NUMPY (missing: NUMPY_INCLUDE_FOUND NUMPY_VERSION_FOUND) 
-- Could NOT find MPI4PY (missing: MPI4PY_INCLUDE_FOUND MPI4PY_VERSION_FOUND) 
-- Found SWIG: TRUE
-- Python 3 features -- not found. Requires Python, SWIG, numpy, and mpi4py if compiling with MPI
```

`brew install python` followed by `pip3 install numpy mtplotlib mpi4py` will likely fix this issue. If it does not, then paths may need to be set to point to the python 3 install.

**Comment by elbashandy** [comment] 2020-02-07 23:08
The problem is fixed by installing numpy `pip3 install numpy...`.

I realized that a lot of tests are missing with the ubuntu container test, and they are complete with `fedora`. I found the difference between the two: `LibXLSXWriter` is found in fedora, but not in ubuntu:

```
Could NOT find LibXLSXWriter (missing: LIBXLSXWRITER_LIBRARY LIBXLSXWRITER_INCLUDE_DIR) 
-- libxlsxwriter features -- not found. set LIBXLSXWRITER_DIR to enable.
```

The fedora setup is pulling `LibXLSXWriter` from `https://github.com/jmcnamara/libxlsxwriter.git`
And ubuntu is pulling from `http://github.com/burlen/libxlsxwriter.git`

I remember that @burlen & @taobrienlbl discussed changes about how teca should deal with `LibXLSXWriter`. Please let me know if I can accommodate the changes that you want to happen.

**Comment by burlen** [comment] 2020-02-07 23:17
Hi Abdel, The missing tests are not related to libxlsx, none of the tests depend on it nor use it.

**Closed** 2020-02-07 23:21 UTC

**Comment by elbashandy** [comment] 2020-02-08 00:51
@burlen the reason I suspected `LibXLSXWriter` was the error I got when I was testing setup.py in #256. I tried replacing the repo with the ubuntu script and it did run all the missing tests on branch `fix_ubuntu_tests`:

https://cdash.nersc.gov/buildSummary.php?buildid=25489
