### ISSUE TITLE
Enhanced error handling

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#527] opened 2021-01-05 20:45 UTC
In a Tues 1/5/21 mtg between @burlen and @taobrienlbl, we discussed modifying TECA's error handling to allow a callback to be provided.  This would enable applications to supply their own error handlers or perhaps to choose between several default error handlers (similar to MPI abort).  These default handlers would need to be implemented.

This came up in the context of adding a way for an application to print a unique message if and only if the pipeline completes without error; this would allow for a bash script to easily detect and log a failed run when doing a large batch of TECA jobs (e.g., on multiple CMIP6 directories).

**Comment by burlen** [comment] 2021-01-12 23:13
this is a duplicate of #38

**Closed** 2021-08-31 20:22 UTC
Labels: 2_medium_priority
