### ISSUE TITLE
TECA needs a CF2 output mechanism

### ISSUE THREAD

**Issue by jnjohnsonlbl** [LBL-EESA/TECA#8] opened 2016-02-01 21:43 UTC
As we start to add more general filters to TECA, we are going to want the option of generating output in the form of a Climate/Forecasting (CF2) NetCDF file. See conventions here: http://cfconventions.org/

**Comment by burlen** [comment] 2019-05-14 18:53
duplicate of #212

**Closed** 2019-05-21 23:38 UTC
Labels: duplicate, feature
