### ISSUE TITLE
setup.py install bug on NERSC

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#254] opened 2019-06-13 16:33 UTC
@burlen - I'm taking the e-mail chain I started this morning and putting it into an issue.

I'm running into a build failure using the `python setup.py install` with the most recent TECA commit at NERSC:
```
CMake Error at apps/cmake_install.cmake:108 (file):
  file INSTALL cannot find
  "/global/cscratch1/sd/taobrien/TECA/build/temp.linux-x86_64-3.6/apps/../bin/teca_convert_table".
Call Stack (most recent call first):
  cmake_install.cmake:75 (include)
```

If I look in the above 'bin' directory, I see the following files:

```
teca_convert_table.py     teca_tc_stats.py
teca_dataset_metadata.py  teca_tc_trajectory
teca_event_filter.py      teca_tc_trajectory_scalars.py
teca_metadata_probe       teca_tc_wind_radii
teca_tc_detect            teca_tc_wind_radii_stats.py
```

So it looks like `teca_convert_table.py` exists, but not teca_convert_table.

In tracking this down, I think this might be related to a recent change to `CMake/teca_python.cmake` associated with #249 (commit 85d8d93).

If I make the following change to add the `.py` suffix to the app name, the setup.py install completes successfully:

```diff
diff --git a/CMake/teca_python.cmake b/CMake/teca_python.cmake
index 035f592..b082ea8 100644
--- a/CMake/teca_python.cmake
+++ b/CMake/teca_python.cmake
@@ -29,7 +29,7 @@ function(teca_py_install_apps)
                 ${CMAKE_CURRENT_BINARY_DIR}/../${BIN_PREFIX}/${appname}.py
                 @ONLY)
             list(APPEND pyapps
-                ${CMAKE_CURRENT_BINARY_DIR}/../${BIN_PREFIX}/${appname})
+                ${CMAKE_CURRENT_BINARY_DIR}/../${BIN_PREFIX}/${appname}.py)
         endforeach()
         install(PROGRAMS ${pyapps} DESTINATION ${BIN_PREFIX})
         # TODO compile the sources
```

As far as I can tell, this should be a problem with any type of install: not just setup.py.  If so though, why would this not be a problem in the test suite, but it is a problem at NERSC?

**Comment by elbashandy** [comment] 2019-06-13 23:57
@taobrienlbl I think I know where the issue is. I am not sure if our tests include testing setup.py.

Just added to `.py` in:
```
list(APPEND pyapps
                ${CMAKE_CURRENT_BINARY_DIR}/../${BIN_PREFIX}/${appname})
```
I created a branch for it `bug_pyapps_fix`. Give it a try.

**Comment by burlen** [comment] 2019-06-17 07:20
@elbashandy @taobrienlbl 

Hi Guys,  I'm re-opening this one and assigning it to @elbashandy  as the fix that was merged is a continuation of the original issue introduced in 85d8d9337.  The problem in 85d8d9337 there is that the application names were mistakingly changed to include a `.py` extension which they should not have.

@elbashandy , Would you please revisit this issue, revert 748ded0 and fix the change you made in 85d8d9337 that added the `.py` extension to applications?

**Comment by burlen** [comment] 2019-06-17 12:51
@elbashandy I was poking around this morning and decided to fix this. please give #257 a review

**Comment by elbashandy** [comment] 2019-06-17 17:47
@burlen Thank you. Done reviewing it.

**Closed** 2019-06-18 12:30 UTC
Labels: bug
